### ISSUE TITLE
crash on load (using v1.7.0-pre.2)

### ISSUE THREAD

**Issue by WickedSchnitzel** [NerdScurvy/CarryOn#16]
Running on 64 bit Windows with 32723 MB RAM
Game Version: v1.19.0-pre.9 (Unstable)
11.12.2023 10:04:16: Critical error occurred in the following mod: carryon@1.7.0-pre.2
Loaded Mods: furniturelibrary@1.0.9, spyglass@0.4.7, game@1.19.0-pre.9, carryon@1.7.0-pre.2, commonlib@2.2.0, creative@1.19.0-pre.9, survival@1.19.0-pre.9, workbenchexpansion@1.8.0, awearablelight@1.0.10, cob@1.5.3, cobserver@1.0.0, em@2.5.0-pre.1, bricklayers@2.5.0-pre.1
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at CarryOn.Client.EntityCarryRenderer.RenderAllCarried(EntityAgent entity, Single deltaTime, Boolean isShadowPass)
   at CarryOn.Client.EntityCarryRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 191
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 862
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 11.12.2023 10:02:28, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x7b60
Startzeit der fehlerhaften Anwendung: 0x01da2c106ee80e7f
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 3974bcb6-121a-4864-b045-3b060337fc9f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 11.12.2023 09:03:36, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.0.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x81f4
Startzeit der fehlerhaften Anwendung: 0x01da2c086747cd97
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 2b27431a-6e50-45c5-98ef-05d5f77f6b72
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by NerdScurvy** [comment]
Was fixed
