### ISSUE TITLE
crash when connecting to server (1.19.0-pre.9)

### ISSUE THREAD

**Issue by WickedSchnitzel** [NerdScurvy/CarryOn#17]
Game Version: v1.19.0-pre.9 (Unstable)
14.12.2023 10:23:45: Critical error occurred in the following mod: carryon@1.7.0-pre.2
Loaded Mods: weaponpacka@1.3.1, Ceramos@0.4.3, chiseltools@1.10.0, pantherinae@1.0.9, millwright@1.1.3, moreicons_cs@1.1.0, primitivesurvival@3.4.3, spyglass@0.4.7, Swordz@1.1.4, translocatorengineeringredux@1.4.9, game@1.19.0-pre.9, alphaweaponpackfix@1.0.0, barbershop@0.4.0, beehivekiln@1.5.1, blacksmithenhancements@1.0.3, carryon@1.7.0-pre.2, commonlib@2.2.0, fairplayguardian@1.1.4, fromgoldencombs@1.4.25, icecold@0.5.1, sailboat@1.2.4, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.0, rivers@1.1.1, snowballs@1.0.1, steadycam@1.2.0, stonebakeoven@1.1.1, creative@1.19.0-pre.9, vsinstruments@1.2.4, vsquest@1.0.0, survival@1.19.0-pre.9, workbenchexpansion@1.8.0, awearablelight@1.0.10, cob@1.5.3, cobserver@1.0.0, em@2.5.0-pre.1, rifteye@0.3.2, simplewinddirection@1.0.2, stonequarry@3.1.7, wolftaming@2.0.1, bricklayers@2.5.0-pre.1
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at CarryOn.Client.EntityCarryRenderer.RenderAllCarried(EntityAgent entity, Single deltaTime, Boolean isShadowPass)
   at CarryOn.Client.EntityCarryRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in G:\git\github\Nerdscurvy\CarryOn\src\Client\EntityCarryRenderer.cs:line 86
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 191
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 862
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by NerdScurvy** [comment]
Fixed a while back. Closing old ticket.
