### ISSUE TITLE
Crash on clients pre 10

### ISSUE THREAD

**Issue by Manic-C-Lo** [NerdScurvy/CarryOn#18]
Client will hit a point where they crash. Relogging causes them to immediately crash.

Will attempt to narrow down cause

[crash.txt](https://github.com/NerdScurvy/CarryOn/files/13751696/crash.txt)

**Comment by MagnusWestin** [comment]
Crashed when trying to put down a reed chest in 1.19

Game Version: v1.19.0 (Stable)
1/17/2024 9:05:49PM: Critical error occurred in the following mod: carryon@1.7.0-pre.3
Loaded Mods: nailsmold@1.0.1, game@1.19.0, betterfirepit@1.1.3, carryon@1.7.0-pre.3, farmlanddropssoil@1.4.0, hudclock@3.4.0, creative@1.19.0, survival@1.19.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.HasAnimal(ItemStack itemStack) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 31
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 123
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 814
   at CarryOn.API.Common.CarriedBlock.PlaceDown(IWorldAccessor world, BlockSelection selection, Entity entity, Boolean dropped, Boolean playSound) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlock.cs:line 195
   at CarryOn.API.Common.CarriedBlockExtensions.PlaceCarried(IPlayer player, BlockSelection selection, CarrySlot slot) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlockExtensions.cs:line 135
   at CarryOn.Common.CarryHandler.PlaceDown(IPlayer player, CarriedBlock carried, BlockSelection selection, BlockPos& placedAt) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 525
   at CarryOn.Common.CarryHandler.OnGameTick(Single deltaTime) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 252
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by MagnusWestin** [comment]
it seems to be related to the new feature where you can trap animals in reed chests

it crashes in this function
Vintagestory.GameContent.BlockBehaviorCreatureContainer.HasAnimal(ItemStack itemStack)

**Comment by NerdScurvy** [comment]
Fixed a while back. I should check this issue list more often 😄
