### ISSUE TITLE
Crashes on setting held item down

### ISSUE THREAD

**Issue by boundingbox** [NerdScurvy/CarryOn#19]
Yes, I'm aware you haven't updated to 1.19.0 stable yet, but heads up for making the update:

```
Running on 64 bit Linux (Linux Mint 21.3) [Kernel 5.15.0.91] with 15906 MB RAM
Game Version: v1.19.0 (Stable)
18/01/2024 05:57:37: Critical error occurred in the following mod: carryon@1.7.0-pre.3
Loaded Mods: fireclayfrompanning@1.0.0, HangingOilLamps@1.0.1, immersivecorpsedrop@1.0.1, juicyores@1.0.0, larchtannin@1.1.0, pieontheshelf@1.0.0, potontheshelf@1.0.0, rackablefirestarter@1.0.0, ragnamans-seeds-from-crops-recipes@1.0.0, roas@1.0.0, spidersilk@1.2.2, sticksfromfirewood@1.0.0, temporalstormgear@1.0.1, TheShovelerRises@1.0.0, visibleore@1.0.1, game@1.19.0, carryon@1.7.0-pre.3, fromgoldencombs@1.4.25, hudclock@3.4.0, scarecrow@1.3.1, simpleemotemenu@1.1.0, useplanksinpitkiln@1.1.1, vesselbuff@1.0.6, vtpp@1.1.0, creative@1.19.0, survival@1.19.0, workbenchexpansion@1.8.0, buzzybees@1.0.0, catchablebees@1.0.0, plumpkins@1.0.0, treetapping@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.HasAnimal(ItemStack itemStack) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 31
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 123
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 791
   at CarryOn.API.Common.CarriedBlock.PlaceDown(IWorldAccessor world, BlockSelection selection, Entity entity, Boolean dropped, Boolean playSound) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlock.cs:line 195
   at CarryOn.API.Common.CarriedBlockExtensions.PlaceCarried(IPlayer player, BlockSelection selection, CarrySlot slot) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlockExtensions.cs:line 135
   at CarryOn.Common.CarryHandler.PlaceDown(IPlayer player, CarriedBlock carried, BlockSelection selection, BlockPos& placedAt) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 525
   at CarryOn.Common.CarryHandler.OnGameTick(Single deltaTime) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 252
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by MuscleLord** [comment]
I have same crash on 1.19.0 (stable)

Running on 64 bit Windows 10.0.19045.0 with 16266 MB RAM
Game Version: v1.19.0 (Stable)
2024-01-19 14:01:22: Critical error occurred in the following mod: carryon@1.7.0-pre.3
Loaded Mods: autoclose@1.0.1, cellardoor@1.4.0, chiseltools@1.10.1, sticksfromboards@1.0.1, game@1.19.0, egocaribautomapmarkers@3.0.1, carryon@1.7.0-pre.3, commonlib@2.3.2, hudclock@3.4.0, creative@1.19.0, survival@1.19.0, playercorpse@1.9.0, tieredtradebags@1.0.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.HasAnimal(ItemStack itemStack) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 31
   at Vintagestory.GameContent.BlockBehaviorCreatureContainer.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode) in VSSurvivalMod\BlockBehavior\BehaviorCreatureContainer.cs:line 123
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 814
   at CarryOn.API.Common.CarriedBlock.PlaceDown(IWorldAccessor world, BlockSelection selection, Entity entity, Boolean dropped, Boolean playSound) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlock.cs:line 195
   at CarryOn.API.Common.CarriedBlockExtensions.PlaceCarried(IPlayer player, BlockSelection selection, CarrySlot slot) in G:\git\github\Nerdscurvy\CarryOn\src\API\Common\CarriedBlockExtensions.cs:line 135
   at CarryOn.Common.CarryHandler.PlaceDown(IPlayer player, CarriedBlock carried, BlockSelection selection, BlockPos& placedAt) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 525
   at CarryOn.Common.CarryHandler.OnGameTick(Single deltaTime) in G:\git\github\Nerdscurvy\CarryOn\src\Common\CarryHandler.cs:line 252
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by NerdScurvy** [comment]
Ah - that was when they added the animal trap.
Was fixed way back.
